version: '3.9'
services:
  python-server:
    container_name: python-server
    build: .
    image: python-server
    ports:
      - "8080:8080"
    volumes:
      - servervol:/serverdata
volumes:
  servervol:
    name: servervol